// window.moradata = {
// 	"status":0,
// 	"message":null,
// 	"data":[{"source":"http://dev.englishtown.com/community/dailylesson/mobile/268/zh-cn","poster":"http://b2cglobaluat.englishtown.com/_vids/dailylesson/lesson/268/poster.jpg","src_culture_desc":"学完这一课，你将能用邮件介绍你自己。","tar_culture_desc":"By the end of this lesson, you will be able to introduce yourself by email.\r\n"},{"source":"http://dev.englishtown.com/community/dailylesson/mobile/267/zh-cn","poster":"http://b2cglobaluat.englishtown.com/_vids/dailylesson/lesson/267/poster.jpg","src_culture_desc":"学完这一课，你将能学会如何给电话号码。","tar_culture_desc":"By the end of this lesson, you will be able to give phone numbers.\r\n"},{"source":"http://dev.englishtown.com/community/dailylesson/mobile/266/zh-cn","poster":"http://b2cglobaluat.englishtown.com/_vids/dailylesson/lesson/266/poster.jpg","src_culture_desc":"学完这一课，你将能自我介绍。","tar_culture_desc":"By the end of this lesson, you will be able to introduce yourself.\r\n"},{"source":"http://dev.englishtown.com/community/dailylesson/mobile/265/zh-cn","poster":"http://b2cglobaluat.englishtown.com/_vids/dailylesson/lesson/265/poster.jpg","src_culture_desc":"这节课结束后，您将能用英语问候别人。","tar_culture_desc":"By the end of this lesson, you will be able to greet people."}]
// };
window.provinceList = {
	"status":0,
	"message":null,
	"data":[
		"beijing","anhui","jiangsu"
	]
}
window.moradata = {
	"status":0,
	"message":null,
	"data":[
		{
			"province":"beijing",
			"cities":[
				{
					"name":"beijing",
					"quxian":[
						{
							"name":"ab","shop":["1","2"]
						},
						{
							"name":"ac","shop":["3","4"]
						},
						{
							"name":"ac","shop":["5","6"]
						},
						{
							"name":"ad","shop":["7","8"]
						}
					]
				},
				{
					"name":"add",
					"quxian":[
						{
							"name":"ae","shop":["9","10"]
						},
						{
							"name":"af","shop":["11","12"]
						},
						{
							"name":"ag","shop":["13","14"]
						},
						{
							"name":"ah","shop":["15","16"]
						}
					]
				}
			]
		},
		{
			"province":"anhui",
			"cities":[
				{
					"name":"wuhu",
					"quxian":[
						{
							"name":"ai","shop":["17","18"]
						},
						{
							"name":"aj","shop":["19","20"]
						},
						{
							"name":"ak","shop":["21","22"]
						},
						{
							"name":"al","shop":["23","24"]
						}
					]
				},
				{
					"name":"hefei",
					"quxian":[
						{
							"name":"am","shop":["25","26"]
						},
						{
							"name":"an","shop":["27","28"]
						},
						{
							"name":"ao","shop":["29","30"]
						},
						{
							"name":"ap","shop":["31","32"]
						}
					]
				}
			]
		},
		{
			"province":"jiangsu",
			"cities":[
				{
					"name":"suzhou",
					"quxian":[
						{
							"name":"aq","shop":["33","34"]
						},
						{
							"name":"ar","shop":["35","36"]
						},
						{
							"name":"s","shop":["37","38"]
						},
						{
							"name":"t","shop":["39","40"]
						}
					]
				},
				{
					"name":"huaian",
					"quxian":[
						{
							"name":"u","shop":["41","42"]
						},
						{
							"name":"v","shop":["43","44"]
						},
						{
							"name":"w","shop":["45","46"]
						},
						{
							"name":"x","shop":["47","48"]
						}
					]
				}
			]
		}
	]
}
// window.moradata = {
// 	provinces:[
// 				{name:"北京",cities:[{name:"北京市",quxian:["海淀区","朝阳区","东城区","西城区"]}]}, 
// 				{name:"安徽省",cities:[{name:"芜湖市",quxian:["繁昌县","芜湖县","南陵县","三山区"]},{name:"合肥市",quxian:["肥西县","蜀山区","庐阳区"]}]}, 
// "湖北省" 
// ]}; 